version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jesus
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jesus
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://jesus:123456@mongo:27017/
      ME_CONFIG_MONGODB_AUTH_DATABASE: pruebasDB
#                                      Users:passowrd:host
      # ME_CONFIG_MONGODB_URL: mongodb://jesus:123456@localhost:27017/
  
volumes:
  mongo-db:
    external: false